kind: pipeline
type: exec
name: runner-test

steps:
  - name: ssh-ing
    image: appleboy/drone-ssh
    settings:
      host: 13.250.98.118
      username: ubuntu
      key: 
        from_secret: ssh-passkey
      port: 22
      script:
        - echo "Hello"
      
  - name: Build
    commands: 
      - echo "Deleting Old Build"
      - rm -r -f /home/ubuntu/testing-golang
      - echo "Starting Build"
      - mkdir -p /home/ubuntu/testing-golang
      - cd /home/ubuntu/testing-golang
      - git clone https://github.com/ridhokurniawan-u/Dummy-Website.git
      - cd /home/ubuntu/testing-golang/Dummy-Website
      - go mod init mango
      - go mod tidy
      - CGO_ENABLED=0 GOOS=linux go build -o testing-maingo

  - name: Deploy
    commands:
      - echo "Killing Old Deploy"
      - |
        PIDS=$(pidof testing-maingo)
        if [ -n "$PIDS" ]; then
          sudo kill -9 $PIDS
          echo "Process 'testing-maingo' terminated."
        else
          echo "No process found for 'testing-maingo'."
        fi
      - echo "Deploying"
      - cd /home/ubuntu/testing-golang/Dummy-Website
      - nohup ./testing-maingo > nohup.out 2>&1 &
      - sleep 5
      - echo "Deployed"
  

  - name: Goofy ahh
    commands:
      - echo "Hello, World!"
      - echo "( ͡° ͜ʖ ͡°)"
      - echo "Ghost Commit"
