- name: Build
  hosts: localhost
  tasks:
  - name: Delete Old Directory
    ansible.builtin.shell: "rm -rf /tmp/Dummy-Website"
      
  - name: Clone Approved Product
    ansible.builtin.git:
      repo: https://github.com/ridhokurniawan-u/Dummy-Website.git
      dest: /tmp/Dummy-Website
      force: yes
  
  - name: Init Go Module
    ansible.builtin.command: "go mod init mango"
    args:
      chdir: /tmp/Dummy-Website
    environment:
      PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

  - name: Tidy up Go module
    ansible.builtin.command: "go mod tidy"
    args:
      chdir: /tmp/Dummy-Website
    environment:
      PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
  
  - name: Compile Go Code
    ansible.builtin.command: 
      cmd: "go build -o testing-maingo"
      chdir: /tmp/Dummy-Website
    environment:
      CGO_ENABLED: "0"
      GOOS: "linux"
      PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

  - name: Ensure build artifact exists
    ansible.builtin.stat:
      path: "/tmp/Dummy-Website/testing-maingo"
    register: build_artifact

  - name: Debug build status
    ansible.builtin.debug:
      msg: "Build {{ 'successful' if build_artifact.stat.exists else 'failed' }}. Binary located at /tmp/Dummy-Website/testing-maingo."
