- name: My First Playbook
  hosts: myhosts
  tasks:
  - name: pinging hosts
    ansible.builtin.ping:
    
  - name: Display Output
    ansible.builtin.debug:
      var: disk_usage.stdout_lines

  - name: Backup old files
    ansible.builtin.shell: |
      cd /home/ubuntu/Dummy-Website
      if [ ! -s testing-maingo-bak ]; then
        echo "Backup file is empty or does not exist. Skipping delete old backup process."
      else
        rm testing-maingo-bak
      fi

      if [ ! -s testing-maingo ]; then
        echo "Backup file is empty or does not exist. Skipping backup process."
      else
        mv testing-maingo testing-maingo-bak
          if [ $? -eq 0 ]; then
            echo "File renamed successfully"
          else
            echo "Rename failed."
          fi
      fi

  - name: Cloning Git
    ansible.builtin.shell: |
      git clone https://github.com/ridhokurniawan-u/Dummy-Website.git
      cd /home/ubuntu/Dummy-Website
      go mod init mango
      go mod tidy
      CGO_ENABLED=0 GOOS=linux go build -o testing-maingo

  - name: Checking old service
    ansible.builtin.command: "pidof testing-maingo"
    register: pidof_result
    ignore_errors: yes

  - name: Kill process
    ansible.builtin.shell: "sudo kill -9 {{ pidof_result.stdout }}"
    when: pidof_result.stdout != ""
      
  - name: Running Service with nohup
    ansible.builtin.shell: |
      cd /home/ubuntu/Dummy-Website
      nohup ./testing-maingo > nohup.out 2>&1 &
      tail nohup.out
    register: deploy_logs
